In [51]:
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import time
from sklearn.decomposition import PCA, TruncatedSVD
def qr_algorithm(A, max_iterations=1000, tolerance=1e-10):
    """
    Compute all eigenvalues and eigenvectors using NumPy's eigendecomposition.
    This is the NumPy/scikit-learn version that replaces the custom QR algorithm.
    
    Parameters:
    A (numpy.ndarray): Square matrix
    max_iterations (int): Maximum number of iterations (not used with NumPy but kept for API compatibility)
    tolerance (float): Convergence tolerance (not used with NumPy but kept for API compatibility)
    
    Returns:
    tuple: (eigenvalues, eigenvectors)
    """
    # Use NumPy's eigendecomposition directly
    eigenvalues, eigenvectors = np.linalg.eig(A)
    
    # Sort by absolute value
    idx = np.argsort(-np.abs(eigenvalues))
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]
    
    return eigenvalues, eigenvectors
def qr_algorithm_example():
    """Example of using the QR algorithm for eigendecomposition."""
    # Define a symmetric matrix
    A = np.array([
        [4, 2, 1],
        [2, 5, 3],
        [1, 3, 6]
    ])
    
    print("\n=== QR Algorithm Example (Using NumPy) ===")
    print("Original Matrix:")
    print(A)
    
    # Find all eigenvalues and eigenvectors
    eigenvalues, eigenvectors = qr_algorithm(A)
    
    print("\nEigenvalues:")
    print(eigenvalues)
    print("\nEigenvectors (columns):")
    print(eigenvectors)
    
    # Verify the results
    print("\nVerification for each eigenpair:")
    for i in range(len(eigenvalues)):
        v = eigenvectors[:, i]
        lambda_val = eigenvalues[i]
        Av = np.dot(A, v)
        lambda_v = lambda_val * v
        error = np.linalg.norm(Av - lambda_v)
        print(f"Eigenpair {i+1}: Error = {error:.10f}")
qr_algorithm_example()


=== QR Algorithm Example (Using NumPy) ===
Original Matrix:
[[4 2 1]
 [2 5 3]
 [1 3 6]]

Eigenvalues:
[9.34849393 3.73015912 1.92134694]

Eigenvectors (columns):
[[-0.3650547  -0.77587586  0.5145403 ]
 [-0.63657455 -0.19527095 -0.74608451]
 [-0.67934373  0.59990492  0.42261825]]

Verification for each eigenpair:
Eigenpair 1: Error = 0.0000000000
Eigenpair 2: Error = 0.0000000000
Eigenpair 3: Error = 0.0000000000


In [52]:
def custom_pca(X, n_components=None):
    """
    Perform Principal Component Analysis on the data using scikit-learn.
    
    Parameters:
    X (numpy.ndarray): Data matrix (samples x features)
    n_components (int): Number of components to keep
    
    Returns:
    tuple: (transformed_data, components, explained_variance, explained_variance_ratio)
    """
    # Use scikit-learn PCA
    pca = PCA(n_components=n_components)
    transformed_data = pca.fit_transform(X)
    
    # Components in scikit-learn are stored differently (transposed compared to our convention)
    components = pca.components_.T
    explained_variance = pca.explained_variance_
    explained_variance_ratio = pca.explained_variance_ratio_
    
    return transformed_data, components, explained_variance, explained_variance_ratio

def pca_example():
    """Example of using PCA on a simple dataset."""
    # Create a simple dataset
    X = np.array([
        [2.5, 2.4],
        [0.5, 0.7],
        [2.2, 2.9],
        [1.9, 2.2],
        [3.1, 3.0],
        [2.3, 2.7],
        [2.0, 1.6],
        [1.0, 1.1],
        [1.5, 1.6],
        [1.1, 0.9]
    ])
    
    print("\n=== PCA Example (Using scikit-learn) ===")
    print("Original Data (10 samples, 2 features):")
    print(X)
    
    # Run scikit-learn PCA
    transformed_data, components, variance, variance_ratio = custom_pca(X)
    
    print("\nPrincipal Components:")
    print(components)
    print(f"Explained Variance: {variance}")
    print(f"Explained Variance Ratio: {variance_ratio * 100}%")
    print(f"Transformed Data (first 3 samples):")
    print(transformed_data[:3])
    
   
pca_example()



=== PCA Example (Using scikit-learn) ===
Original Data (10 samples, 2 features):
[[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]

Principal Components:
[[ 0.6778734   0.73517866]
 [ 0.73517866 -0.6778734 ]]
Explained Variance: [1.28402771 0.0490834 ]
Explained Variance Ratio: [96.31813143  3.68186857]%
Transformed Data (first 3 samples):
[[ 0.82797019  0.17511531]
 [-1.77758033 -0.14285723]
 [ 0.99219749 -0.38437499]]


In [55]:
def custom_svd(A):
    """
    Perform Singular Value Decomposition on a matrix using NumPy.
    
    Parameters:
    A (numpy.ndarray): Input matrix
    
    Returns:
    tuple: (U, S, V^T) where U contains left singular vectors,
           S is a diagonal matrix of singular values, and V^T
           contains right singular vectors.
    """
    # Get the shape of the matrix
    m, n = A.shape
    
    # Use NumPy's SVD
    U, s, Vt = np.linalg.svd(A, full_matrices=True)
    
    # Create the diagonal matrix of singular values
    S = np.zeros((m, n))
    min_dim = min(m, n)
    for i in range(min_dim):
        S[i, i] = s[i]
    
    return U, S, Vt

def svd_example():
    """Example of using SVD on a simple matrix."""
    # Define a simple matrix
    A = np.array([
        [1, 0, 0, 0, 2],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 4, 0, 0, 0]
    ])
    
    print("\n=== SVD Example (Using NumPy) ===")
    print("Original Matrix:")
    print(A)
    
    # Run NumPy SVD
    U, S, Vt = custom_svd(A)
    
    # Get the diagonal elements of S
    s_values = np.diag(S)[:min(A.shape)]
    
    print("\nU (left singular vectors):")
    print(U)
    print("\nSingular values:")
    print(s_values)
    print("\nV^T (right singular vectors transposed):")
    print(Vt)
    
    # Reconstruct the original matrix
    reconstructed = np.dot(U, np.dot(S, Vt))
    
    print("\nReconstructed Matrix:")
    print(reconstructed)
    print(f"Reconstruction Error: {np.linalg.norm(A - reconstructed):.10f}")
svd_example()


=== SVD Example (Using NumPy) ===
Original Matrix:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 4 0 0 0]]

U (left singular vectors):
[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 1.  0.  0.  0.]]

Singular values:
[4.         3.         2.23606798 0.        ]

V^T (right singular vectors transposed):
[[-0.          1.          0.          0.          0.        ]
 [-0.          0.          1.          0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]

Reconstructed Matrix:
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]]
Reconstruction Error: 0.0000000000


In [56]:
def performance_comparison():
    """Compare the performance of scikit-learn/NumPy implementations with custom implementations."""
    print("\n=== Performance Comparison ===")
    
    # Create matrices of different sizes
    sizes = [10, 50, 100]
    
    print("Matrix Size | Custom Eigen | NumPy Eigen | Ratio | Custom PCA  | Scikit PCA | Ratio | Custom SVD  | NumPy SVD  | Ratio")
   
    
    for size in sizes:
        # Create a random symmetric matrix for eigenvalue tests
        A = np.random.rand(size, size)
        A = (A + A.T) / 2  # Make it symmetric for real eigenvalues
        
        # Data for PCA
        X = np.random.rand(size*2, size)  # More samples than features
        
        # Time custom qr algorithim
        start = time.time()
        qr_algorithm(A)
        custom_eigen_time = time.time() - start
        
        # Time NumPy eigendecomposition
        start = time.time()
        np.linalg.eigh(A)
        numpy_eigen_time = time.time() - start
        
        # Calculate ratio (how many times faster NumPy is)
        eigen_ratio = custom_eigen_time / numpy_eigen_time if numpy_eigen_time > 0 else float('inf')
        
        # Time custom PCA
        start = time.time()
        custom_pca(X)
        custom_pca_time = time.time() - start
        
        # Time scikit-learn PCA
        start = time.time()
        pca = PCA()
        pca.fit_transform(X)
        scikit_pca_time = time.time() - start
        
        # Calculate ratio (how many times faster scikit-learn is)
        pca_ratio = custom_pca_time / scikit_pca_time if scikit_pca_time > 0 else float('inf')
        
        # Time custom SVD
        start = time.time()
        custom_svd(A)
        custom_svd_time = time.time() - start
        
        # Time NumPy SVD
        start = time.time()
        np.linalg.svd(A)
        numpy_svd_time = time.time() - start
        
        # Calculate ratio (how many times faster NumPy is)
        svd_ratio = custom_svd_time / numpy_svd_time if numpy_svd_time > 0 else float('inf')
        
        print(f"{size:10d} | {custom_eigen_time:11.6f} | {numpy_eigen_time:11.6f} | {eigen_ratio:5.1f}x | "
              f"{custom_pca_time:10.6f} | {scikit_pca_time:10.6f} | {pca_ratio:5.1f}x | "
              f"{custom_svd_time:11.6f} | {numpy_svd_time:10.6f} | {svd_ratio:5.1f}x")


# Run the examples
if __name__ == "__main__":
    # Set random seed for reproducibility
    np.random.seed(42)
    
    # Run examples
    qr_algorithm_example()
    pca_example()
    svd_example()
    
    # Compare performance
    performance_comparison()


=== QR Algorithm Example (Using NumPy) ===
Original Matrix:
[[4 2 1]
 [2 5 3]
 [1 3 6]]

Eigenvalues:
[9.34849393 3.73015912 1.92134694]

Eigenvectors (columns):
[[-0.3650547  -0.77587586  0.5145403 ]
 [-0.63657455 -0.19527095 -0.74608451]
 [-0.67934373  0.59990492  0.42261825]]

Verification for each eigenpair:
Eigenpair 1: Error = 0.0000000000
Eigenpair 2: Error = 0.0000000000
Eigenpair 3: Error = 0.0000000000

=== PCA Example (Using scikit-learn) ===
Original Data (10 samples, 2 features):
[[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]

Principal Components:
[[ 0.6778734   0.73517866]
 [ 0.73517866 -0.6778734 ]]
Explained Variance: [1.28402771 0.0490834 ]
Explained Variance Ratio: [96.31813143  3.68186857]%
Transformed Data (first 3 samples):
[[ 0.82797019  0.17511531]
 [-1.77758033 -0.14285723]
 [ 0.99219749 -0.38437499]]

=== SVD Example (Using NumPy) ===
Original Matrix:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 4 